version: 1.0.{build}
build:
  project: osu-collection-manager.sln
  verbosity: minimal
install:
  - cmd: git submodule update --init --recursive"
  - cmd: nuget restore osu-collection-manager.sln
  - cmd: nuget restore OsuMapDownload.sln
  - cmd: nuget restore osu-database-reader.sln